language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn lint
  - yarn global add codecov
  - yarn test --coverage --bail
  - codecov
  - yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
  on:
    branch: master